export const diagramLabels = {
  hero: "An illustrative AI answer assembling from four answer engines, listing three fictional brands, with a fourth row marked not mentioned.",
  shift: "A comparison of two journeys: a search results list that continues beyond the frame, and an AI answer that names three brands and ends.",
  consideration: "A single illustrative AI answer, highlighted three ways in turn to show discovery, recommendation and supporting evidence.",
  evidence: "An illustrative claim from an AI answer, connected to the source attached to it, with the connection then marked as association rather than cause.",
  dimensions: "Seven measurement dimensions arranged around a brand at the centre, each connected to the part of an AI answer it reads.",
  movement: "A four-step loop — measure, diagnose, fix, verify — above five surfaces that shape what an AI answer says.",
  truth: "Three pages of one website stating the same fact differently, resolving into a single ruled record.",
  work: "A stack of five delivered content guides beside a list of what each contained.",
} as const;

export const homepage = {
  demoUrl: "https://www.linkedin.com/in/vishal-kumar-gupta-b5a664252/",
  primaryCta: "Get a free demo",
  secondaryCta: "Discuss your brand",
  blocks: {
    hero: {
      number: "01",
      eyebrow: "ANSWER ENGINE OPTIMISATION, END TO END",
      headline: ["Be the brand", "AI recommends."],
      descriptor: "Measure what AI says about your brand. Find what sits behind it. Fix it. Verify the change.",
      lead: "When a buyer asks an assistant what to buy, a few brands make the consideration set. Whether yours is one of them is observable, and the reasons are addressable.",
      micro: "Start with a free view of how AI sees your brand.",
      notMentioned: "Not mentioned",
      notMentionedDetail: "Absent from this answer. Not ranked low — not surfaced.",
      rail: [
        { number: "01", label: "Measure" },
        { number: "02", label: "Diagnose" },
        { number: "03", label: "Fix" },
        { number: "04", label: "Verify" },
      ],
      railCaption: "From AI answers to work you can publish.",
    },
    shift: {
      number: "02",
      eyebrow: "THE NEW BUYING JOURNEY",
      headline: ["More decisions now", "start with an answer."],
      lead: "Customers increasingly ask AI what to buy, use or consider. A few brands make the consideration set. The rest stay invisible.",
      traditionalLabel: "TRADITIONAL SEARCH",
      traditionalCaption: "Many links. Many options. The journey continues.",
      answerLabel: "AI ANSWER",
      answerCaption: "A few recommendations. The question often ends here.",
      link: "See why it matters",
      linkHref: "/why-ai-answers",
    },
    consideration: {
      number: "03",
      eyebrow: "THREE SIGNALS THAT MATTER",
      headline: ["Being in the answer", "is not being chosen."],
      lead: "The question underneath everything: is your brand entering the customer's consideration set?",
      note: "A simplified public view. What sits behind it is measured in more detail.",
      link: "Explore how it works",
      linkHref: "/measurement",
      cards: [
        { name: "Discovered", icon: "Discovered", tone: "blue", copy: "You enter the answer when the buyer describes the need and never names you." },
        { name: "Recommended", icon: "Recommended", tone: "orange", copy: "The answer puts you forward as a strong fit, not one more name in a list." },
        { name: "Reinforced", icon: "Reinforced", tone: "green", copy: "What's said about you stays accurate, consistent and supported as the buyer keeps asking." },
      ],
    },
    evidence: {
      number: "04",
      eyebrow: "WHAT THE ANSWER IS BUILT ON",
      headline: ["Every finding shows", "the answer it came from."],
      lead: "What AI actually said, and what supports the finding. Quoted, kept, re-readable.",
      limitOne: "A cited source shows the engine linked it to a nearby claim. It does not prove the source caused the recommendation.",
      limitTwo: "Answers shift by engine, question, time and context. A single answer is an observation, not a rank.",
      link: "See how measurement works",
      linkHref: "/measurement",
    },
    dimensions: {
      number: "05",
      eyebrow: "A CONNECTED VIEW",
      headline: ["Seven dimensions.", "One clear picture."],
      lead: "How AI finds, reads, trusts and represents your brand. One measurement system — each dimension explains a different part of the same answer.",
      nucleus: "Your brand in AI answers",
      note: "Where evidence is thin, a component is marked not computable. Never scored zero.",
      link: "See all dimensions",
      linkHref: "/measurement",
      items: [
        { group: "FOUND", name: "AI Shortlisting", question: "Do you make the shortlist when nobody names you?", tone: "blue" },
        { group: "FOUND", name: "Category Demand Capture", question: "Are you capturing the category demand you already sit close to?", tone: "blue" },
        { group: "TRUSTED", name: "Brand Credentials", question: "Could an engine actually find proof of who you are and what qualifies you?", tone: "green" },
        { group: "TRUSTED", name: "Brand Authority", question: "How much independent standing sits behind you, next to the brands engines name instead?", tone: "green" },
        { group: "READ AND REPRESENTED", name: "Machine Readiness", question: "Can AI access, parse and correctly understand the information that matters?", tone: "orange" },
        { group: "READ AND REPRESENTED", name: "Brand Perception", question: "What does an engine say when someone simply asks about you?", tone: "blue" },
        { group: "READ AND REPRESENTED", name: "AI Framing", question: "When a sceptical buyer asks the hard question, does the engine clear the worry or confirm it?", tone: "orange" },
      ],
    },
    movement: {
      number: "06",
      eyebrow: "FROM MEASUREMENT TO MOVEMENT",
      headline: ["A dashboard can show the gap.", "It does not close it."],
      lead: "Measurement alone does not change the underlying problem.",
      second: "And content is only one part of it. Product information, technical structure, evidence and authority all shape what an engine says.",
      note: "The same questions on both ends, so the second reading measures your brand changing rather than the questions changing.",
      link: "See what changes",
      linkHref: "/fixes",
      steps: ["Measure", "Diagnose", "Fix", "Verify"],
      surfaces: [
        { name: "Product information", state: "Addressed" },
        { name: "Technical structure", state: "Addressed" },
        { name: "Content", state: "Addressed" },
        { name: "Evidence", state: "Implicated" },
        { name: "Authority", state: "Implicated" },
      ],
    },
    artifacts: {
      number: "07",
      eyebrow: "FROM INSIGHT TO ARTIFACT",
      headline: ["What the work", "produces."],
      lead: "A clear diagnosis, a prioritised plan and implementation-ready fixes. Components are included where relevant to your business.",
      link: "See what you get",
      linkHref: "/fixes",
      close: "wrath produces the approved work and the implementation package. Your team or your partners publish and implement where required.",
      items: [
        { number: "01", name: "Baseline", icon: "Baseline", descriptor: "Where you stand across the dimensions measured.", fragment: { type: "states", dimension: "AI Shortlisting", states: ["Measured", "Not computable"] } },
        { number: "02", name: "Evidence", icon: "Evidence", descriptor: "What each engine said, quoted verbatim and retained.", fragment: { type: "evidence" } },
        { number: "03", name: "Diagnosis", icon: "Diagnosis", descriptor: "The specific page, source or response the gap traces back to.", fragment: { type: "line", line: "Product page — cooling claim not stated in visible copy" } },
        { number: "04", name: "Action plan", icon: "Action plan", descriptor: "What changes, in what order, and why that order.", fragment: { type: "priorities", rows: ["Priority 1 — product page copy", "Priority 2 — structured data parity", "Priority 3 — comparison content"] } },
        { number: "05", name: "Fixes", icon: "Fixes", descriptor: "The technical corrections and the content itself, implementation-ready.", fragment: { type: "fix", headings: ["Fix", "Acceptance criterion"], value: "Structured data matches visible copy" } },
        { number: "06", name: "Brand Source of Truth", icon: "Brand Source of Truth", descriptor: "The approved factual foundation everything is written from.", fragment: { type: "ruled", rows: ["Fabric composition", "Care instructions"], state: "Ruled" } },
        { number: "07", name: "Verification", icon: "Verification", descriptor: "The same questions, re-run against the same baseline.", fragment: { type: "verification", labels: ["Before", "After"] } },
      ],
      measured: "Measured",
    },
    truth: {
      number: "08",
      eyebrow: "THE FACTUAL FOUNDATION",
      headline: ["One approved", "factual foundation", "for everything", "your brand says."],
      lead: "Contradictions in your own published story get found and ruled on, not quietly averaged away.",
      third: "The foundation the content and technical fixes are written from, so every fix says the same thing.",
      link: "How the Brand Source of Truth works",
      linkHref: "/brand-source-of-truth",
    },
    work: {
      number: "09",
      eyebrow: "REAL WORK · CLIENT ANONYMISED",
      headline: ["Shoppers comparing", "cooling sheets had", "no straight answer."],
      lead: "A consumer bedding brand needed clearer AI visibility for its key buying decisions.",
      panelOne: "5 buying guides delivered",
      panelOneItems: ["Cooling sheets", "Hot sleepers", "Heat and moisture comfort", "Materials and cooling claims", "Care and usage"],
      panelTwo: "Each guide included",
      panelTwoItems: ["Finished copy", "Product and supporting links", "Publishing guidance", "Structured-data materials prepared"],
      bound: "Delivered and prepared. Deployment and live-page verification are separate milestones. No change in AI recommendations is claimed.",
      link: "Know more about it",
      linkHref: "/work/bedding-content",
    },
    close: {
      number: "10",
      fitEyebrow: "WHO THIS IS FOR",
      fitHeadline: ["Built for brands whose", "buyers already moved."],
      verticals: ["E-commerce and D2C", "SaaS", "Services", "Healthcare", "Education"],
      triggers: ["Organic traffic holding while discovery falls.", "Engines describing you with stale facts, and no way to see it.", "Needing a defensible baseline before spending on AI content."],
      link: "Who this fits",
      linkHref: "/who-we-work-with",
      facts: [],
      headline: "Find out what the answer says about you.",
      lead: "A free demo on your domain. A focused, fast view of AI visibility and page readiness where there's enough data, showing the largest observed leaks and the evidence behind each.",
    },
  },
} as const;
