/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandSourceOfTruthRouteImport } from './routes/brand-source-of-truth'
import { Route as FixesRouteImport } from './routes/fixes'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MeasurementRouteImport } from './routes/measurement'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as WhoWeWorkWithRouteImport } from './routes/who-we-work-with'
import { Route as WhyAiAnswersRouteImport } from './routes/why-ai-answers'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkBeddingContentRouteImport } from './routes/work.bedding-content'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSourceOfTruthRoute = BrandSourceOfTruthRouteImport.update({
  id: '/brand-source-of-truth',
  path: '/brand-source-of-truth',
  getParentRoute: () => rootRouteImport,
} as any)
const FixesRoute = FixesRouteImport.update({
  id: '/fixes',
  path: '/fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementRoute = MeasurementRouteImport.update({
  id: '/measurement',
  path: '/measurement',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeWorkWithRoute = WhoWeWorkWithRouteImport.update({
  id: '/who-we-work-with',
  path: '/who-we-work-with',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyAiAnswersRoute = WhyAiAnswersRouteImport.update({
  id: '/why-ai-answers',
  path: '/why-ai-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkRoute,
} as any)
const WorkBeddingContentRoute = WorkBeddingContentRouteImport.update({
  id: '/bedding-content',
  path: '/bedding-content',
  getParentRoute: () => WorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-source-of-truth': typeof BrandSourceOfTruthRoute
  '/fixes': typeof FixesRoute
  '/library': typeof LibraryRoute
  '/measurement': typeof MeasurementRoute
  '/styleguide': typeof StyleguideRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/why-ai-answers': typeof WhyAiAnswersRoute
  '/work': typeof WorkRouteWithChildren
  '/work/bedding-content': typeof WorkBeddingContentRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-source-of-truth': typeof BrandSourceOfTruthRoute
  '/fixes': typeof FixesRoute
  '/library': typeof LibraryRoute
  '/measurement': typeof MeasurementRoute
  '/styleguide': typeof StyleguideRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/why-ai-answers': typeof WhyAiAnswersRoute
  '/work/bedding-content': typeof WorkBeddingContentRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/brand-source-of-truth': typeof BrandSourceOfTruthRoute
  '/fixes': typeof FixesRoute
  '/library': typeof LibraryRoute
  '/measurement': typeof MeasurementRoute
  '/styleguide': typeof StyleguideRoute
  '/who-we-work-with': typeof WhoWeWorkWithRoute
  '/why-ai-answers': typeof WhyAiAnswersRoute
  '/work': typeof WorkRouteWithChildren
  '/work/bedding-content': typeof WorkBeddingContentRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/brand-source-of-truth'
    | '/fixes'
    | '/library'
    | '/measurement'
    | '/styleguide'
    | '/who-we-work-with'
    | '/why-ai-answers'
    | '/work'
    | '/work/bedding-content'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/brand-source-of-truth'
    | '/fixes'
    | '/library'
    | '/measurement'
    | '/styleguide'
    | '/who-we-work-with'
    | '/why-ai-answers'
    | '/work/bedding-content'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/brand-source-of-truth'
    | '/fixes'
    | '/library'
    | '/measurement'
    | '/styleguide'
    | '/who-we-work-with'
    | '/why-ai-answers'
    | '/work'
    | '/work/bedding-content'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BrandSourceOfTruthRoute: typeof BrandSourceOfTruthRoute
  FixesRoute: typeof FixesRoute
  LibraryRoute: typeof LibraryRoute
  MeasurementRoute: typeof MeasurementRoute
  StyleguideRoute: typeof StyleguideRoute
  WhoWeWorkWithRoute: typeof WhoWeWorkWithRoute
  WhyAiAnswersRoute: typeof WhyAiAnswersRoute
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-source-of-truth': {
      id: '/brand-source-of-truth'
      path: '/brand-source-of-truth'
      fullPath: '/brand-source-of-truth'
      preLoaderRoute: typeof BrandSourceOfTruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixes': {
      id: '/fixes'
      path: '/fixes'
      fullPath: '/fixes'
      preLoaderRoute: typeof FixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurement': {
      id: '/measurement'
      path: '/measurement'
      fullPath: '/measurement'
      preLoaderRoute: typeof MeasurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-work-with': {
      id: '/who-we-work-with'
      path: '/who-we-work-with'
      fullPath: '/who-we-work-with'
      preLoaderRoute: typeof WhoWeWorkWithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-ai-answers': {
      id: '/why-ai-answers'
      path: '/why-ai-answers'
      fullPath: '/why-ai-answers'
      preLoaderRoute: typeof WhyAiAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/bedding-content': {
      id: '/work/bedding-content'
      path: '/bedding-content'
      fullPath: '/work/bedding-content'
      preLoaderRoute: typeof WorkBeddingContentRouteImport
      parentRoute: typeof WorkRoute
    }
  }
}

interface WorkRouteChildren {
  WorkBeddingContentRoute: typeof WorkBeddingContentRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkBeddingContentRoute: WorkBeddingContentRoute,
  WorkIndexRoute: WorkIndexRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BrandSourceOfTruthRoute: BrandSourceOfTruthRoute,
  FixesRoute: FixesRoute,
  LibraryRoute: LibraryRoute,
  MeasurementRoute: MeasurementRoute,
  StyleguideRoute: StyleguideRoute,
  WhoWeWorkWithRoute: WhoWeWorkWithRoute,
  WhyAiAnswersRoute: WhyAiAnswersRoute,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
